version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestTempProject
  gitServerName: test1
  gitUrl: https://github.com/PoojaAnandGit/TestTempProject
  gitUsername: PoojaAnandGit
  gitBranch: main
